import Link from 'next/link';
import {notFound,redirect} from 'next/navigation';
import {AppShell} from '@/components/app-shell';
import {currentUser} from '@/lib/auth';
import {dayLabel} from '@/lib/calendar';
import {availableStatisticsUnit,coverageLabel,monthlyStatistics,reportFilters,statisticsUnits} from '@/lib/report-statistics';
import {statusLabel} from '@/lib/utils';
import {monthlyExecutive} from '@/lib/monthly-executive';
import {MonthlyExecutiveDashboard} from '@/components/monthly-executive-dashboard';

export default async function MonthlyReports({searchParams}:{searchParams:Promise<{mes?:string;unidade?:string;ok?:string;erro?:string}>}){
  const user=await currentUser();if(!user)redirect('/login');
  const query=await searchParams;let filters;try{filters=reportFilters(query);}catch{return <AppShell user={user} active="monthly"><h1 className="title">Relatórios Mensais</h1><p className="error">Escolha um mês válido.</p><Link className="btn btn-soft" href="/relatorios-mensais">Voltar aos filtros</Link></AppShell>;}
  if(!availableStatisticsUnit(user,filters.unit))notFound();
  const units=statisticsUnits(user),data=monthlyStatistics(user,filters),executive=monthlyExecutive(user,filters),parameters=new URLSearchParams({mes:filters.month,unidade:filters.unit}),documents=data.coverage.filter(row=>row.type==='documents');
  const documentary=documents.reduce((result,row)=>({answered:result.answered+row.uniqueAnswered,applicable:result.applicable+row.uniqueApplicable}),{answered:0,applicable:0});
  return <AppShell user={user} active="monthly"><header className="topbar"><div><div className="eyebrow">Síntese executiva do mês</div><h1 className="title">Relatórios Mensais</h1><p className="muted">Indicadores, comparação de unidades, prioridades e parecer para o cliente.</p></div><a className="btn btn-primary" href={`/api/monthly-reports?${parameters}`}>Baixar PDF mensal</a></header>
    {query.ok==='1'&&<p className="notice success-notice" role="status">Parecer revisado salvo.</p>}{query.erro&&<p className="error" role="alert">{query.erro==='stale'?'Os indicadores mudaram. Recarregue e confira o parecer antes de salvar.':'Não foi possível salvar o parecer. Confira os dados e tente novamente.'}</p>}
    <section className="card"><form method="get" className="search-form monthly-filters"><div className="field"><label htmlFor="monthly-month">MÊS DA VISITA</label><input id="monthly-month" type="month" name="mes" min="1900-01" max="2200-12" required defaultValue={filters.month}/></div><div className="field"><label htmlFor="monthly-unit">UNIDADE</label><select id="monthly-unit" name="unidade" defaultValue={filters.unit}><option value="">Todas as unidades</option>{units.map(unit=><option key={unit.id} value={unit.id}>{unit.code} — {unit.name}{user.role==='SUPER_ADMIN'?` (${unit.company_name})`:''}</option>)}</select></div><button className="btn btn-soft">Filtrar</button></form><p className="muted">O período considera a data da visita em America/Sao_Paulo.</p></section>
    <MonthlyExecutiveDashboard data={executive} canReview={user.role!=='INSPECTOR'} returnTo="monthly" showCompany={user.role==='SUPER_ADMIN'}/>
    <details className="monthly-operational"><summary>Acompanhamento operacional e cobertura dos relatórios</summary><p className="muted">Esta seção também inclui relatórios recebidos que aguardam aprovação. Rascunhos e cancelados ficam fora; respostas e situações mostram o estado atual dos relatórios.</p>
    <div className="grid stats" style={{marginTop:18}}>{[['Visitas agendadas',data.scheduled],['Relatórios recebidos',data.received],['Relatórios aprovados',data.approved],['Respostas por visita',data.counts.answered],['Respostas conformes',data.counts.compliant],['Respostas não conformes',data.counts.noncompliant],['Cobertura documental no mês',coverageLabel(documentary.answered,documentary.applicable)],['Não se aplica / sem classificação',`${data.counts.notApplicable} / ${data.counts.unclassified}`]].map(([label,value])=><div className="card" key={label}><div className="stat-head">{label}</div><div className="stat-value" style={typeof value==='string'?{fontSize:18}:undefined}>{value}</div></div>)}</div><p className="notice" style={{marginTop:18}}>Cobertura única do checklist no mês: <b>{coverageLabel(data.uniqueCoverage.answered,data.uniqueCoverage.applicable)}</b></p>
    <div className="section-head"><div><h2>Por unidade</h2><p>{dayLabel(filters.month+'-01',{month:'long',year:'numeric'})}</p></div></div><section className="card report-table-scroll" tabIndex={0} role="region" aria-label="Estatísticas por unidade"><table className="report-table"><thead><tr><th>Unidade</th><th>Visitas agendadas</th><th>Relatórios recebidos</th><th>Aprovados</th><th>Cobertura mensal única</th></tr></thead><tbody>{data.units.map(unit=><tr key={unit.id}><td><b>{unit.code}</b><small>{unit.name}{user.role==='SUPER_ADMIN'?` · ${unit.company_name}`:''}</small></td><td>{unit.scheduled}</td><td>{unit.received}</td><td>{unit.approved}</td><td>{coverageLabel(unit.uniqueAnswered,unit.uniqueApplicable)}</td></tr>)}</tbody></table>{!data.units.length&&<div className="empty-state"><h2>Nenhum registro neste período</h2><p>Agende visitas ou envie os relatórios para revisão para acompanhar os números.</p></div>}</section>
    <div className="section-head"><div><h2>Preenchimento por modelo e área</h2><p>Um item preenchido nas visitas semanais conta uma vez por unidade e modelo no mês.</p></div></div><section className="card report-table-scroll" tabIndex={0} role="region" aria-label="Cobertura de preenchimento por área"><table className="report-table"><thead><tr><th>Modelo / Área / Departamento</th><th>Cobertura mensal única</th><th>Respostas por visita</th><th>Conformes</th><th>Não conformes</th><th>Não se aplica</th><th>Sem classificação</th></tr></thead><tbody>{data.coverage.map(row=><tr key={JSON.stringify([row.template_id,row.area,row.section,row.type])}><td><b>{row.section}</b><small>{row.area} · {row.template_name}</small></td><td>{coverageLabel(row.uniqueAnswered,row.uniqueApplicable)}</td><td>{row.answered}/{row.applicable}</td><td>{row.compliant}</td><td>{row.noncompliant}</td><td>{row.notApplicable}</td><td>{row.unclassified}</td></tr>)}</tbody></table>{!data.coverage.length&&<p className="muted">Sem relatórios recebidos neste mês.</p>}<p className="muted">Cobertura considera a união dos itens aplicáveis no mês por unidade e modelo. Respostas e conformidade são contadas por visita. Condicionais seguem as respostas atuais. Planos e suas verificações ficam fora destes indicadores.</p></section>
    <div className="section-head"><div><h2>Relatórios das visitas do mês</h2></div><Link className="btn btn-soft" href={`/planos-de-acao?${parameters}`}>Ver planos de ação</Link></div><section className="card report-table-scroll" tabIndex={0} role="region" aria-label="Relatórios do mês"><table className="report-table"><thead><tr><th>Unidade</th><th>Data da visita</th><th>Responsável Técnico</th><th>Situação</th><th>Itens respondidos</th><th>Ações</th></tr></thead><tbody>{data.reports.map(report=><tr key={report.id}><td><b>{report.unit_code}</b></td><td>{report.planned_start?dayLabel(report.planned_start,{day:'2-digit',month:'2-digit',year:'numeric'}):'Não informada'}</td><td>{report.inspector_name||'Não informado'}</td><td>{statusLabel(report.status)}</td><td>{report.answered}</td><td><Link className="btn btn-soft" href={`/relatorios/${report.id}`}>Examinar</Link></td></tr>)}</tbody></table>{!data.reports.length&&<p className="muted">Nenhum relatório recebido para visitas neste mês.</p>}</section>
    </details>
  </AppShell>;
}
