import Link from 'next/link';
import {notFound,redirect} from 'next/navigation';
import {AppShell} from '@/components/app-shell';
import {currentUser} from '@/lib/auth';
import {dayLabel} from '@/lib/calendar';
import {availableStatisticsUnit,planFields,reportFilters,statisticsUnits,trackedPlans} from '@/lib/report-statistics';
import {statusLabel} from '@/lib/utils';

export default async function ActionPlans({searchParams}:{searchParams:Promise<{mes?:string;unidade?:string;situacao?:string}>}){
  const user=await currentUser();if(!user)redirect('/login');const query=await searchParams;let filters;
  try{filters=reportFilters(query,false);}catch{return <AppShell user={user} active="plans"><h1 className="title">Planos de Ação</h1><p className="error">Escolha um mês válido.</p><Link className="btn btn-soft" href="/planos-de-acao">Voltar aos filtros</Link></AppShell>;}
  if(!availableStatisticsUnit(user,filters.unit))notFound();
  const units=statisticsUnits(user),all=trackedPlans(user,filters),status=['pending','completed'].includes(query.situacao||'')?query.situacao:'',plans=all.filter(plan=>!status||plan.completed===(status==='completed'));
  return <AppShell user={user} active="plans"><header className="topbar"><div><div className="eyebrow">Controle e acompanhamento</div><h1 className="title">Planos de Ação</h1><p className="muted">Ações registradas nas visitas, com suas verificações posteriores.</p></div><Link className="btn btn-soft" href="/relatorios/novo">Preencher relatório de visita</Link></header>
    <section className="card"><form className="search-form" method="get"><div className="field"><label htmlFor="plans-month">MÊS DA VISITA DE ORIGEM</label><input id="plans-month" type="month" name="mes" min="1900-01" max="2200-12" defaultValue={filters.month}/></div><div className="field"><label htmlFor="plans-unit">UNIDADE</label><select id="plans-unit" name="unidade" defaultValue={filters.unit}><option value="">Todas as unidades</option>{units.map(unit=><option key={unit.id} value={unit.id}>{unit.code} — {unit.name}{user.role==='SUPER_ADMIN'?` (${unit.company_name})`:''}</option>)}</select></div><div className="field"><label htmlFor="plans-status">SITUAÇÃO</label><select id="plans-status" name="situacao" defaultValue={status}><option value="">Todas</option><option value="pending">Pendentes</option><option value="completed">Concluídos</option></select></div><button className="btn btn-soft">Filtrar</button><Link className="btn btn-ghost" href="/planos-de-acao">Limpar</Link></form><p className="muted">Um plano é concluído quando a última verificação aprovada em uma visita posterior da mesma unidade confirma “Sim”. A edição segue a revisão do relatório de origem; relatórios aprovados ficam preservados.</p></section>
    <div className="grid stats" style={{marginTop:18}}>{[['Planos registrados',all.length],['Pendentes',all.filter(plan=>!plan.completed).length],['Concluídos',all.filter(plan=>plan.completed).length]].map(([label,value])=><div className="card" key={label}><div className="stat-head">{label}</div><div className="stat-value">{value}</div></div>)}</div>
    <div className="grid" style={{marginTop:20}}>{plans.map(plan=><article className="card report-plan" key={plan.id}><div className="section-head" style={{marginTop:0}}><div><h2>{plan.unit_code} · {plan.department}</h2><p>{plan.date?`Visita de ${dayLabel(plan.date)}`:'Data da visita não informada'}{user.role==='SUPER_ADMIN'?` · ${plan.company_name}`:''}</p></div><span className={`badge ${plan.completed?'success':'warn'}`}>{plan.completed?'Concluído':'Pendente'}</span></div><p className="muted">Relatório de origem: {statusLabel(plan.report_status)}</p><dl className="report-plan-details">{planFields.map(([field,label])=><div key={field}><dt>{label}</dt><dd>{plan.details[field]||'Não informado'}</dd></div>)}</dl>
      {plan.verification?<div className="past-plan"><h3>Última verificação</h3><p className="muted">{dayLabel(plan.verification.date)} · {statusLabel(plan.verification.status)}</p><p>Concluído? <b>{plan.verification.answer}</b></p>{plan.verification.comment&&<p className="report-transcript">{plan.verification.comment}</p>}{plan.verification.status!=='APPROVED'&&<p className="muted">Esta verificação ainda depende de aprovação. A situação acima considera apenas verificações aprovadas.</p>}<Link className="btn btn-soft" href={`/relatorios/${plan.verification.inspection_id}`}>Examinar verificação</Link></div>:<p className="muted">Ainda sem verificação em uma visita posterior.</p>}
      <Link className="btn btn-ghost" href={`/relatorios/${plan.inspection_id}`}>Examinar relatório de origem</Link>
    </article>)}</div>{!plans.length&&<section className="card empty-state" style={{marginTop:20}}><h2>Nenhum plano encontrado</h2><p>Os planos preenchidos nos relatórios enviados para revisão aparecem aqui.</p></section>}
  </AppShell>;
}
