import Link from 'next/link';
import {notFound,redirect} from 'next/navigation';
import {currentUser} from '@/lib/auth';
import {db} from '@/lib/db';
import {AppShell} from '@/components/app-shell';
import {ConfirmSubmit} from '@/components/confirm-submit';

type Row={id:string;inspection_id:string;item_id:string|null;title:string;severity:string;status:string;due_date:string|null;responsible:string|null;action_plan:string|null;company_id:string;inspector_id:string|null;control_code:string;inspection_title:string;unit_name:string;item_title:string|null;item_code:string|null};

export default async function NCDetails({params,searchParams}:{params:Promise<{id:string}>;searchParams:Promise<{ok?:string;erro?:string}>}){
  const user=await currentUser();if(!user)redirect('/login');const {id}=await params;
  const row=db.prepare('SELECT n.*,i.company_id,i.inspector_id,i.control_code,i.title inspection_title,u.name unit_name,ti.title item_title,ti.code item_code FROM nonconformities n JOIN inspections i ON i.id=n.inspection_id JOIN units u ON u.id=i.unit_id LEFT JOIN template_items ti ON ti.id=n.item_id WHERE n.id=?').get(id) as Row|undefined;
  if(!row||user.role!=='SUPER_ADMIN'&&row.company_id!==user.company_id||user.role==='INSPECTOR'&&row.inspector_id!==user.id)notFound();
  const query=await searchParams;const canManage=user.role!=='INSPECTOR';
  return <AppShell user={user} active="nc"><header className="topbar"><div><div className="eyebrow">{row.control_code} · {row.unit_name}</div><h1 className="title">{row.title}</h1></div><Link className="btn btn-ghost" href={`/inspecoes/${row.inspection_id}`}>Abrir inspeção</Link></header>{query.ok&&<div className="notice success-notice">{query.ok==='rejeitada'?'Não conformidade rejeitada sem apagar o histórico.':'Plano de ação atualizado.'}</div>}{query.erro&&<div className="error">Revise os campos informados.</div>}
    <section className="grid two-col"><div className="card"><div className="eyebrow">ITEM RELACIONADO</div><h2 style={{fontSize:17}}>{row.item_code?`${row.item_code} · `:''}{row.item_title||'Observação extraordinária'}</h2><p className="muted">{row.inspection_title}</p><div className="evidence-pills"><span className="badge warn">Criticidade {row.severity}</span><span className="badge">{row.status}</span></div></div><div className="card"><div className="eyebrow">PRAZO ATUAL</div><div className="stat-value" style={{fontSize:20}}>{row.due_date?new Date(`${row.due_date}T12:00:00`).toLocaleDateString('pt-BR'):'A definir'}</div><div className="muted">Responsável: {row.responsible||'A definir'}</div></div></section>
    <div className="section-head"><div><h2>Plano de ação</h2><p>Responsável, prazo, tratamento e encerramento.</p></div></div>
    {canManage?<><form className="card form-card" action={`/api/nonconformities/${id}`} method="post"><div className="grid form-grid"><div className="field"><label>RESPONSÁVEL</label><input name="responsible" required defaultValue={row.responsible||''}/></div><div className="field"><label>PRAZO</label><input name="due_date" required type="date" defaultValue={row.due_date||''}/></div><div className="field"><label>STATUS</label><select name="status" defaultValue={row.status}><option value="OPEN">Aberta</option><option value="IN_PROGRESS">Em tratamento</option><option value="RESOLVED">Resolvida</option><option value="CLOSED">Encerrada</option><option value="REJECTED">Rejeitada</option></select></div><div className="field field-wide"><label>AÇÃO CORRETIVA E EVIDÊNCIA DE TRATAMENTO</label><textarea name="action_plan" rows={5} required defaultValue={row.action_plan||''}/></div></div><div className="form-actions"><Link className="btn btn-ghost" href="/nao-conformidades">Voltar</Link><button className="btn btn-primary">Salvar plano de ação</button></div></form>{row.status!=='REJECTED'&&<form className="danger-zone" action={`/api/nonconformities/${id}`} method="post"><input type="hidden" name="intent" value="reject"/><div><b>Rejeitar não conformidade</b><p>Ela sairá das pendências ativas, mas continuará disponível na auditoria e na inspeção.</p></div><ConfirmSubmit label="Rejeitar registro" message="Rejeitar esta não conformidade mantendo seu histórico?"/></form>}</>:<div className="card"><p style={{whiteSpace:'pre-wrap'}}>{row.action_plan||'O Supervisor ainda não registrou o plano de ação.'}</p><div className="muted">O Inspetor pode consultar, mas não alterar o tratamento.</div></div>}
  </AppShell>;
}
