'use client';

import {useState} from 'react';
import Link from 'next/link';
import type {ExecutiveMonthly,ExecutiveUnit} from '@/lib/monthly-executive';

const percent=(value:number|null)=>value===null?'Sem dados':`${value.toLocaleString('pt-BR',{maximumFractionDigits:1})}%`;
const delta=(value:number|null)=>value===null?'Sem comparação':`${value>0?'+':''}${value.toLocaleString('pt-BR',{maximumFractionDigits:1})} p.p.`;
type Sort='code'|'igc'|'delta'|'documents'|'reincidence';

export function MonthlyExecutiveDashboard({data,canReview,returnTo,showCompany=false}:{data:ExecutiveMonthly;canReview:boolean;returnTo:'dashboard'|'monthly';showCompany?:boolean}){
  const [sort,setSort]=useState<Sort>('igc'),[ascending,setAscending]=useState(false),[search,setSearch]=useState('');
  const value=(unit:ExecutiveUnit,column:Sort)=>column==='code'?unit.code:column==='igc'?unit.metrics.igc:column==='delta'?unit.delta:column==='documents'?unit.metrics.documentPercent:unit.metrics.reincidence;
  const normalize=(text:string)=>text.toLocaleLowerCase('pt-BR').normalize('NFD').replace(/[\u0300-\u036f]/g,'');
  const rows=data.units.filter(unit=>normalize(`${unit.code} ${unit.name}${showCompany?` ${unit.company_name}`:''}`).includes(normalize(search))).sort((a,b)=>{
    const left=value(a,sort),right=value(b,sort);
    if(left===null)return right===null?a.code.localeCompare(b.code):1;
    if(right===null)return -1;
    const difference=typeof left==='string'&&typeof right==='string'?left.localeCompare(right,'pt-BR',{numeric:true}):Number(left)-Number(right);
    return difference*(ascending?1:-1)||a.code.localeCompare(b.code);
  });
  function order(column:Sort){if(sort===column)setAscending(!ascending);else{setSort(column);setAscending(column==='code');}}
  function winners(column:'igc'|'documentPercent'|'reincidence'|'delta',lowest=false){
    const metric=(unit:ExecutiveUnit)=>column==='delta'?unit.delta:unit.metrics[column];
    const measured=data.units.filter(unit=>metric(unit)!==null);
    if(!measured.length)return [];
    const best=(lowest?Math.min:Math.max)(...measured.map(unit=>metric(unit)!));
    return measured.filter(unit=>metric(unit)===best);
  }
  const bestIgc=winners('igc'),leastVariation=winners('delta',true),mostDocuments=winners('documentPercent'),leastResolved=winners('reincidence',true),metrics=data.metrics;
  const detailsLink=(unit:string)=>`${returnTo==='monthly'?'/relatorios-mensais':'/dashboard'}?${new URLSearchParams({mes:data.filters.month,unidade:unit})}`;
  const columns:{id:Sort;label:string}[]=[{id:'code',label:'Código da unidade'},{id:'igc',label:'IGC do mês'},{id:'delta',label:'Variação vs. mês anterior'},{id:'documents',label:'Documentação pendente'},{id:'reincidence',label:'Índice de Reincidência'}];
  return <div className="monthly-executive">
    <p className="monthly-data-note">Indicadores de {data.reportCount} {data.reportCount===1?'relatório aprovado':'relatórios aprovados'} das visitas do mês. {data.pendingReportCount>0?`${data.pendingReportCount} ${data.pendingReportCount===1?'relatório recebido aguarda':'relatórios recebidos aguardam'} aprovação e ficam fora dos indicadores. `:''}Itens sem resposta ficam fora das taxas; a cobertura mostra o que foi avaliado.</p>
    <section aria-labelledby="monthly-kpis-title"><div className="section-head"><div><div className="eyebrow">Bloco I</div><h2 id="monthly-kpis-title">Dashboard Executivo e KPIs Consolidados</h2></div></div>
      <div className="monthly-kpis">
        <Metric tone="green" label="Índice Global de Conformidade" value={percent(metrics.igc)} note={`${metrics.weightedCompliant.toLocaleString('pt-BR')}/${metrics.weightedEvaluated.toLocaleString('pt-BR')} pontos de conformidade · IGC ponderado`}/>
        <Metric tone="blue" label="Volume de Não Conformidades" value={percent(metrics.sectorPercent)} note={`${metrics.sectorsPending}/${metrics.sectorsTotal} setores com pendências · ${metrics.nonconformities} falhas registradas`}/>
        <Metric tone="purple" label="Documentação Pendente e Indisponível" value={percent(metrics.documentPercent)} note={`${metrics.documentsPending}/${metrics.documentsEvaluated} documentos avaliados com pendência`}/>
        <Metric tone="amber" label="Índice de Reincidência" value={percent(metrics.reincidence)} note={`${metrics.resolutions}/${metrics.plans} planos resolvidos · resoluções ÷ planos`}/>
      </div>
      <div className="monthly-method"><span>IGC considera as respostas Sim/Não classificadas, incluindo documentação, com a resposta esperada do modelo usado na visita. Documentação usa a última resposta do mês por documento e unidade. O percentual de setores considera as pendências técnicas.</span><span>A fórmula de referência para reincidência expressa a taxa de resolução dos planos: quanto maior, mais planos resolvidos. Não equivale à frequência de repetição de falhas.</span><span>Cobertura única do período: <b>{metrics.answered}/{metrics.applicable} itens aplicáveis respondidos por unidade e modelo</b>. Valores sem avaliação aparecem como “Sem dados”.</span></div>
    </section>
    <section aria-labelledby="monthly-ranking-title"><div className="section-head"><div><div className="eyebrow">Bloco II</div><h2 id="monthly-ranking-title">Ranking e Benchmark entre Unidades</h2><p>Compare o IGC, a variação em pontos percentuais e as pendências. Clique no título de uma coluna para ordenar.</p></div></div>
      <div className="monthly-highlights"><Highlight label="Maior IGC" units={bestIgc} metric={unit=>percent(unit.metrics.igc)}/><Highlight label="Menor variação do IGC" units={leastVariation} metric={unit=>delta(unit.delta)}/><Highlight label="Maior pendência documental" units={mostDocuments} metric={unit=>percent(unit.metrics.documentPercent)}/><Highlight label="Menor resolução de planos" units={leastResolved} metric={unit=>percent(unit.metrics.reincidence)}/></div>
      <div className="card monthly-ranking"><div className="field monthly-unit-search"><label htmlFor="monthly-ranking-search">LOCALIZAR UNIDADE NA MATRIZ</label><input id="monthly-ranking-search" type="search" value={search} onChange={event=>setSearch(event.target.value)} placeholder="Código ou nome da unidade"/></div><div className="report-table-scroll" tabIndex={0} role="region" aria-label="Matriz de comparação entre unidades"><table className="report-table monthly-matrix"><caption className="sr-only">Indicadores mensais. Variação do IGC comparada a {data.previousMonth}; unidades sem avaliação não entram nos destaques.</caption><thead><tr>{columns.map(column=><th key={column.id} scope="col" aria-sort={sort===column.id?ascending?'ascending':'descending':'none'}><button type="button" className="monthly-sort" onClick={()=>order(column.id)}>{column.label}<span aria-hidden="true">{sort===column.id?ascending?'↑':'↓':'↕'}</span></button></th>)}</tr></thead><tbody>{rows.map(unit=><tr key={unit.id}><th scope="row"><Link className="unit-link" href={detailsLink(unit.id)}>{unit.code}</Link><small>{unit.name}{showCompany?` · ${unit.company_name}`:''}</small><small>{unit.reportCount} {unit.reportCount===1?'relatório aprovado':'relatórios aprovados'}</small></th><td><b>{percent(unit.metrics.igc)}</b></td><td><span className={unit.delta===null?'muted':unit.delta>0?'monthly-positive':unit.delta<0?'text-danger':''}>{delta(unit.delta)}</span></td><td>{percent(unit.metrics.documentPercent)}<small>{unit.metrics.documentsPending}/{unit.metrics.documentsEvaluated} documentos</small></td><td>{percent(unit.metrics.reincidence)}<small>{unit.metrics.resolutions}/{unit.metrics.plans} planos resolvidos</small></td></tr>)}</tbody></table></div>{!rows.length&&<p className="monthly-empty">{search?'Nenhuma unidade corresponde à busca.':'Nenhuma unidade disponível neste período.'}</p>}</div>
    </section>
    <section aria-labelledby="monthly-pareto-title"><div className="section-head"><div><div className="eyebrow">Bloco III</div><h2 id="monthly-pareto-title">Gestão de Planos de Ação e Reincidências</h2><p>Análise de Pareto: os 8 motivos mais frequentes nas não conformidades do mês.</p></div><Link className="btn btn-soft" href={`/planos-de-acao?${new URLSearchParams({mes:data.filters.month,unidade:data.filters.unit})}`}>Ver planos de ação</Link></div>
      <div className="card monthly-pareto">{data.pareto.length?<><div className="monthly-chart-legend"><span><i className="monthly-bar-key"/>Ocorrências</span><span><i className="monthly-line-key"/>Percentual acumulado</span></div><ParetoChart data={data}/><div className="report-table-scroll" tabIndex={0} role="region" aria-label="Motivos observados e percentual acumulado"><table className="report-table monthly-causes"><thead><tr><th scope="col">N.º / motivo observado</th><th scope="col">Ocorrências</th><th scope="col">Participação</th><th scope="col">Acumulado</th></tr></thead><tbody>{data.pareto.map((cause,index)=><tr key={`${index}-${cause.label}`}><th scope="row"><span className="monthly-cause-index">{index+1}</span>{cause.label}</th><td>{cause.count}</td><td>{percent(cause.share)}</td><td>{percent(cause.cumulativePercent)}</td></tr>)}</tbody></table></div><p className="muted">Participação e acumulado consideram {data.paretoTotal} ocorrências. Os motivos são extraídos das respostas dos relatórios; a causa-raiz deve ser confirmada pela equipe.</p></>:<div className="monthly-empty"><b>{data.reportCount?'Nenhuma não conformidade classificada no mês.':'Aguardando relatórios aprovados para montar o Pareto.'}</b><p>O gráfico aparece quando houver motivos registrados nas avaliações.</p></div>}</div>
    </section>
    <section aria-labelledby="monthly-conclusion-title"><div className="section-head"><div><div className="eyebrow">Bloco IV</div><h2 id="monthly-conclusion-title">Conclusão Técnica e Parecer Sintético</h2><p>Resumo do mês para a diretoria e a qualidade, com revisão do Coordenador.</p></div></div>
      <div className="card monthly-conclusion">{data.review?.current?<p className="badge success">Parecer revisado por {data.review.reviewed_by} · {new Date(data.review.reviewed_at).toLocaleString('pt-BR',{timeZone:'America/Sao_Paulo'})}</p>:<p className="badge warn">{data.review?'Indicadores alterados — nova revisão necessária':'Parecer automático — aguardando revisão'}</p>}
        <p className="monthly-conclusion-text">{data.review?.current?data.review.text:data.automaticConclusion}</p>
        {data.review&&!data.review.current&&<details className="monthly-prior-review"><summary>Ver parecer da revisão anterior</summary><p className="monthly-conclusion-text">{data.review.text}</p><p className="muted">{data.review.reviewed_by} · {new Date(data.review.reviewed_at).toLocaleString('pt-BR',{timeZone:'America/Sao_Paulo'})}</p></details>}
        {canReview&&<details className="monthly-review-form"><summary className="btn btn-soft">{data.review?.current?'Editar parecer revisado':'Revisar parecer'}</summary><form action="/api/monthly-reports/review" method="post"><input type="hidden" name="mes" value={data.filters.month}/><input type="hidden" name="unidade" value={data.filters.unit}/><input type="hidden" name="source_hash" value={data.sourceHash}/><input type="hidden" name="return_to" value={returnTo}/><div className="field"><label htmlFor="monthly-conclusion-review">PARECER DO COORDENADOR</label><textarea id="monthly-conclusion-review" name="text" rows={7} required minLength={20} maxLength={1800} defaultValue={data.review?.current?data.review.text:data.automaticConclusion}/><small className="muted">Até 1.800 caracteres. Confira as prioridades e os indicadores antes de registrar a revisão.</small></div><button className="btn btn-primary">Salvar parecer revisado</button></form></details>}
      </div>
    </section>
  </div>;
}

function Metric({label,value,note,tone}:{label:string;value:string;note:string;tone:string}){return <div className={`monthly-kpi monthly-kpi-${tone}`}><h3>{label}</h3><strong>{value}</strong><p>{note}</p></div>;}
function Highlight({label,units,metric}:{label:string;units:ExecutiveUnit[];metric:(unit:ExecutiveUnit)=>string}){return <div className="monthly-highlight"><span>{label}</span><b>{units.length?units.map(unit=>unit.code).join(', '):'Sem dados'}</b>{units.length>0&&<small>{metric(units[0])}{units.length>1?' · empate':''}</small>}</div>;}
function ParetoChart({data}:{data:ExecutiveMonthly}){
  const width=640,height=260,left=44,right=46,top=20,bottom=40,plotWidth=width-left-right,plotHeight=height-top-bottom,max=Math.max(...data.pareto.map(cause=>cause.count)),step=plotWidth/data.pareto.length;
  const points=data.pareto.map((cause,index)=>`${left+step*(index+.5)},${top+plotHeight*(1-cause.cumulativePercent/100)}`).join(' ');
  return <svg className="monthly-pareto-chart" viewBox={`0 0 ${width} ${height}`} role="img" aria-label="Gráfico de Pareto das não conformidades" aria-describedby="monthly-pareto-description"><desc id="monthly-pareto-description">Barras mostram as ocorrências dos motivos numerados na tabela abaixo. A linha mostra o percentual acumulado de todas as ocorrências do mês.</desc>{[0,.5,1].map(fraction=><g key={fraction}><line x1={left} y1={top+plotHeight*(1-fraction)} x2={width-right} y2={top+plotHeight*(1-fraction)} stroke="#d7e5e1"/><text x={left-8} y={top+plotHeight*(1-fraction)+4} textAnchor="end">{(max*fraction).toLocaleString('pt-BR',{maximumFractionDigits:1})}</text><text x={width-right+8} y={top+plotHeight*(1-fraction)+4}>{fraction*100}%</text></g>)}{data.pareto.map((cause,index)=><g key={index}><rect x={left+step*index+step*.16} y={top+plotHeight*(1-cause.count/max)} width={step*.68} height={plotHeight*cause.count/max} rx={4} fill="#397a67"/><text x={left+step*(index+.5)} y={height-18} textAnchor="middle">{index+1}</text></g>)}<polyline points={points} fill="none" stroke="#aa7a2d" strokeWidth={3}/>{data.pareto.map((cause,index)=><circle key={index} cx={left+step*(index+.5)} cy={top+plotHeight*(1-cause.cumulativePercent/100)} r={4} fill="#aa7a2d" stroke="white" strokeWidth={1.5}/>)}<text x={left} y={height-3}>Motivo observado (n.º)</text></svg>;
}
