'use client';
import Link from 'next/link';
import {useState} from 'react';
import {useRouter} from 'next/navigation';
import {EvidenceInputs} from './evidence-inputs';
import type {InspectionTemplateItem} from '@/lib/inspection-template';
import type {AnswerRow,PriorPlan,ResponseDetails} from '@/lib/received-reports';

type Evidence={id:string;item_id:string;kind:string;original_name:string};
type Props={inspectionId:string;item:InspectionTemplateItem;response?:AnswerRow;details:ResponseDetails;editable:boolean;evidences:Evidence[];plans:PriorPlan[];layout?:'table'|'card';reportArea?:string;conditionalItems?:InspectionTemplateItem[]};
const locations=['Impresso em Pasta Física','Segundo qualidade, disponível para impressão em formato digital'];
const planFields=[['nonconformities','Não Conformidade(s)'],['immediate','Medidas Imediatas'],['corrective','Ação(ões) Corretiva(s)'],['preventive','Ação(ões) Preventiva(s)'],['responsible','Responsáveis']] as const;
export function ReportItemForm({inspectionId,item,response,details,editable,evidences,plans,layout='table',reportArea,conditionalItems=[]}:Props){
  const [answer,setAnswer]=useState(response?.answer||''),[comment,setComment]=useState(response?.comment||'');
  const [checks,setChecks]=useState(details.checks||[]);
  const enabledQuestions=conditionalItems.filter(child=>{try{const rule=JSON.parse(child.condition_json||'{}');return rule.item_id===item.id&&rule.answer===answer;}catch{return false;}});
  const conditionalNotice=editable&&enabledQuestions.length>0?<aside className="notice" role="status"><b>Pergunta complementar habilitada</b>{enabledQuestions.map(child=><p key={child.id}>{child.title}</p>)}<small>Salve e continue para preencher a pergunta complementar. Ela será incluída somente para esta resposta.</small></aside>:null;
  const formId=`report-${item.id}`,action=`/api/inspections/${inspectionId}/responses`;
  const hidden=<><input type="hidden" name="item_id" value={item.id}/><input type="hidden" name="report_view" value="1"/>{layout==='card'&&<><input type="hidden" name="report_wizard" value="1"/><input type="hidden" name="report_area" value={reportArea||item.section||item.area}/></>}</>;
  const history=<Link className="report-history" href={`/inspecoes/${inspectionId}/itens/${item.id}`}>Histórico · {response?.revision||0}</Link>;
  const save=editable?<button className="btn btn-primary" form={formId}>{layout==='card'?'Salvar e continuar':'Salvar'}</button>:null;
  const binary=!editable?<span>{answer||'—'}</span>:<select aria-label={`Resposta: ${item.title}`} form={formId} name="answer" required disabled={!editable} value={answer} onChange={event=>setAnswer(event.target.value)}><option value="">Selecione</option><option>Sim</option><option>Não</option>{item.response_type==='YES_NO_NA'&&<option>Não se aplica</option>}</select>;
  const files=<div className="report-evidences">{evidences.map(evidence=><Link key={evidence.id} target="_blank" href={`/api/evidences/${evidence.id}`}>{evidence.kind==='PHOTO'?'Visualizar foto':evidence.kind==='AUDIO'?'Ouvir áudio':'Visualizar vídeo'} · {evidence.original_name}</Link>)}</div>;
  const cardBinary=!editable?<p><b>Resposta:</b> {answer||'—'}</p>:<fieldset className="report-binary"><legend>{item.response_type==='DOCUMENT'?'Presente e vigente?':'Resposta'}</legend>{['Sim','Não',...(item.response_type==='YES_NO_NA'?['Não se aplica']:[])].map(value=><label className={`btn ${answer===value?'btn-primary':'btn-soft'}`} key={value}><input type="radio" name="answer" value={value} required checked={answer===value} onChange={()=>setAnswer(value)}/>{value}</label>)}</fieldset>;
  if(layout==='card'&&item.response_type==='DOCUMENT')return <article id={item.id} className="card report-question-card"><p className="eyebrow">{item.section}</p><h3>{item.title}</h3><form id={formId} action={action} method="post"><fieldset disabled={!editable}>{hidden}<input type="hidden" name="comment" value={response?.comment||''}/>{cardBinary}<div className="field"><label htmlFor={`${item.id}-location`}>Se sim, vigente em pasta?</label>{!editable?<p>{details.location||'—'}</p>:<select id={`${item.id}-location`} name="location" required={answer==='Sim'} disabled={answer!=='Sim'} defaultValue={details.location||''}><option value="">Selecione</option>{locations.map(value=><option key={value}>{value}</option>)}</select>}</div><div className="field"><label htmlFor={`${item.id}-expiry`}>Vencimento</label>{!editable?<p>{details.expiry?details.expiry.split('-').reverse().join('/'):'—'}</p>:<input id={`${item.id}-expiry`} name="expiry" type="date" defaultValue={details.expiry||''}/>}</div><dl className="report-plan-details"><div><dt>Periodicidade</dt><dd>{item.document_periodicity||'—'}</dd></div><div><dt>Número de exemplares a serem mantidos em pasta</dt><dd>{item.document_copies||'—'}</dd></div></dl></fieldset><div className="report-row-actions">{history}{save}</div></form></article>;
  if(layout==='card'&&!['ACTION_PLAN','PLAN_REVIEW'].includes(item.response_type))return <article id={item.id} className="card report-question-card"><p className="eyebrow">{item.section||item.area}</p><h3>{item.title}</h3>{item.guidance&&<p className="muted">{item.guidance}</p>}<form id={formId} action={action} method="post" encType="multipart/form-data"><fieldset disabled={!editable}>{hidden}{cardBinary}{conditionalNotice}{editable&&<EvidenceInputs compact formId={formId} onTranscript={text=>setComment(current=>[current,text].filter(Boolean).join('\n').slice(0,2000))}/>}<div className="field"><label htmlFor={`${item.id}-comment`}>Transcrição do áudio / Observações (opcional)</label>{!editable?<p className="report-transcript">{comment||'—'}</p>:<textarea id={`${item.id}-comment`} name="comment" maxLength={2000} rows={5} value={comment} onChange={event=>setComment(event.target.value)} placeholder="Grave um áudio ou digite suas observações."/>}</div></fieldset>{files}<div className="report-row-actions">{history}{save}</div></form></article>;
  if(item.response_type==='DOCUMENT')return <tr id={item.id}><td><form id={formId} action={action} method="post">{hidden}<input type="hidden" name="comment" value={response?.comment||''}/></form><b>{item.title}</b>{history}</td><td data-label="Presente e vigente?">{binary}</td><td data-label="Vigente em pasta?">{!editable?<span>{details.location||'—'}</span>:<select form={formId} name="location" aria-label={`Disponibilização: ${item.title}`} disabled={!editable||answer!=='Sim'} required={answer==='Sim'} defaultValue={details.location||''}><option value="">Selecione</option>{locations.map(value=><option key={value}>{value}</option>)}</select>}</td><td data-label="Vencimento">{!editable?<span>{details.expiry?details.expiry.split('-').reverse().join('/'):'—'}</span>:<input form={formId} name="expiry" type="date" aria-label={`Vencimento: ${item.title}`} disabled={!editable} defaultValue={details.expiry||''}/>}</td><td data-label="Periodicidade">{item.document_periodicity||'—'}</td><td data-label="Exemplares em pasta">{item.document_copies||'—'}</td><td>{save}</td></tr>;
  if(item.response_type==='ACTION_PLAN'&&!editable)return <article id={item.id} className="card report-plan"><h3>{item.title}</h3><dl className="report-plan-details">{planFields.map(([field,label])=><div key={field}><dt>{label}</dt><dd>{details[field]||'—'}</dd></div>)}</dl>{history}</article>;
  if(item.response_type==='ACTION_PLAN')return <article id={item.id} className="card report-plan"><h3>{item.title}</h3><form id={formId} action={action} method="post"><fieldset disabled={!editable}>{hidden}<input type="hidden" name="answer" value="Sim"/><input type="hidden" name="comment" value=""/>{planFields.map(([field,label])=><div className="field" key={field}><label htmlFor={`${item.id}-${field}`}>{label}</label><textarea id={`${item.id}-${field}`} name={field} maxLength={2000} rows={3} required={field==='nonconformities'} defaultValue={details[field]||''}/></div>)}</fieldset><div className="report-row-actions">{history}{save}</div></form></article>;
  if(item.response_type==='PLAN_REVIEW')return <article id={item.id} className="card report-plan"><h3>{item.title}</h3><form id={formId} action={action} method="post">{hidden}<input type="hidden" name="answer" value="Sim"/><input type="hidden" name="comment" value=""/><input type="hidden" name="checks" value={JSON.stringify(checks)}/>{!plans.length&&<p className="muted">Nenhum plano aprovado de visita anterior nesta unidade.</p>}{plans.map(plan=>{const check=checks.find(check=>check.id===plan.id);return <div className="past-plan" key={plan.id}><label className="check-option"><input type="checkbox" disabled={!editable} checked={!!check} onChange={event=>setChecks(current=>event.target.checked?[...current,{id:plan.id,answer:'Não',comment:''}]:current.filter(check=>check.id!==plan.id))}/><b>{plan.department} · {plan.date.split('-').reverse().join('/')}</b></label><dl>{planFields.map(([field,label])=><div key={field}><dt>{label}</dt><dd>{plan.details[field]||'—'}</dd></div>)}</dl>{check&&<div className="grid form-grid"><div className="field"><label htmlFor={`check-${plan.id}`}>O plano foi concluído?</label><select id={`check-${plan.id}`} value={check.answer} disabled={!editable} onChange={event=>setChecks(current=>current.map(value=>value.id===plan.id?{...value,answer:event.target.value as 'Sim'|'Não'}:value))}><option>Sim</option><option>Não</option></select></div><div className="field"><label htmlFor={`check-notes-${plan.id}`}>Observações da verificação</label><textarea id={`check-notes-${plan.id}`} value={check.comment} maxLength={2000} disabled={!editable} onChange={event=>setChecks(current=>current.map(value=>value.id===plan.id?{...value,comment:event.target.value}:value))}/></div></div>}</div>;})}<div className="report-row-actions">{history}{editable&&plans.length>0&&<button className="btn btn-primary" disabled={!checks.length}>{layout==='card'?'Salvar e continuar':'Salvar verificações'}</button>}</div></form></article>;
  return <tr id={item.id}><td data-label="Área/Departamento">{item.section||item.area}</td><td data-label="Verificação"><b>{item.title}</b>{item.guidance&&<p className="muted">{item.guidance}</p>}{history}</td><td data-label="Sim / Não">{binary}</td><td data-label="Fotos associadas"><form id={formId} action={action} method="post" encType="multipart/form-data"><fieldset disabled={!editable}>{hidden}{editable&&<EvidenceInputs compact formId={formId} onTranscript={text=>setComment(current=>[current,text].filter(Boolean).join('\n').slice(0,2000))}/>}</fieldset></form>{files}</td><td data-label="Transcrição / Observações">{!editable?<p className="report-transcript">{comment||'—'}</p>:<textarea aria-label={`Transcrição e observações: ${item.title}`} form={formId} name="comment" disabled={!editable} maxLength={2000} rows={4} value={comment} onChange={event=>setComment(event.target.value)}/>} {save}</td></tr>;
}

export function ReportStatusButton({id,status,label,disabled}:{id:string;status:string;label:string;disabled:boolean}){
  const router=useRouter(),[busy,setBusy]=useState(false),[error,setError]=useState('');
  return <div><button className="btn btn-primary" disabled={disabled||busy} onClick={async()=>{setBusy(true);setError('');try{const response=await fetch(`/api/inspections/${id}/status`,{method:'POST',body:new URLSearchParams({status,report_view:'1'})});if(!response.ok){const result=await response.json();setError(result.error||'Não foi possível enviar.');return;}router.refresh();}catch{setError('Falha na conexão. O relatório continua salvo.');}finally{setBusy(false);}}}>{busy?'Enviando…':label}</button>{error&&<p className="error" role="alert">{error}</p>}</div>;
}
