import assert from 'node:assert/strict';
import bcrypt from 'bcryptjs';
import fs from 'node:fs';
import {db} from '../src/lib/db.ts';
import type {SessionUser} from '../src/lib/auth.ts';
import {availableStatisticsUnit,monthlyStatistics,reportFilters,trackedPlans,validMonth} from '../src/lib/report-statistics.ts';

// ponytail: one scoped integration check; records belong only to these temporary companies.
const tag=`monthly-${Date.now()}`,company=tag+'-company',foreign=tag+'-foreign',unit=tag+'-unit',otherUnit=tag+'-other-unit',template=tag+'-template',techId=tag+'-tech',otherTechId=tag+'-other-tech',coordId=tag+'-coord',password='MonthlyReportTest123!';
const tech:SessionUser={id:techId,company_id:company,name:techId,email:techId+'@test.local',role:'INSPECTOR'},coord:SessionUser={...tech,id:coordId,role:'SUPERVISOR'},admin:SessionUser={...coord,company_id:null,role:'SUPER_ADMIN'};
const reports:string[]=[],visits:string[]=[];
async function request(route:string,cookie=''){return fetch('http://localhost:3000'+route,{redirect:'manual',headers:cookie?{cookie}:{}});}
function inspection(suffix:string,date:string,status:string,owner=techId,targetUnit=unit,targetCompany=company){const id=tag+'-'+suffix;reports.push(id);db.prepare('INSERT INTO inspections(id,company_id,unit_id,template_id,control_code,title,status,inspector_id,planned_start,received_at,template_snapshot) VALUES(?,?,?,?,?,?,?,?,?,?,?)').run(id,targetCompany,targetUnit,template,id,id,status,owner,date,['IN_REVIEW','APPROVED','CHANGES_REQUESTED'].includes(status)?date+'T18:00:00Z':null,JSON.stringify({items:db.prepare('SELECT * FROM template_items WHERE template_id=? ORDER BY sort_order').all(template)}));return id;}
function answer(inspectionId:string,item:string,value:string,compliance:string,details:unknown={},current=1){const id=tag+'-response-'+crypto.randomUUID();db.prepare('INSERT INTO responses(id,inspection_id,item_id,user_id,answer,compliance,comment,details_json,is_current) VALUES(?,?,?,?,?,?,?, ?,?)').run(id,inspectionId,tag+'-'+item,techId,value,compliance,'',JSON.stringify(details),current);return id;}
try{
  assert.equal(validMonth('2026-02'),true);assert.equal(validMonth('2026-13'),false);assert.throws(()=>reportFilters({mes:'2026-13'}));
  for(const id of [company,foreign])db.prepare('INSERT INTO companies(id,legal_name,trade_name) VALUES(?,?,?)').run(id,id,id);
  for(const [id,role] of [[techId,'INSPECTOR'],[otherTechId,'INSPECTOR'],[coordId,'SUPERVISOR']])db.prepare('INSERT INTO users(id,company_id,name,email,password_hash,role) VALUES(?,?,?,?,?,?)').run(id,company,id,id+'@test.local',bcrypt.hashSync(password,4),role);
  for(const [id,companyId] of [[unit,company],[otherUnit,foreign]])db.prepare('INSERT INTO units(id,company_id,name,code,responsible_id) VALUES(?,?,?,?,?)').run(id,companyId,id,id,companyId===company?techId:null);
  db.prepare("INSERT INTO templates(id,company_id,name,status) VALUES(?,?,?,'PUBLISHED')").run(template,company,template);
  const items=[['DOC','Documentação','Licenças','DOCUMENT',null],['PARENT','Operação','Portaria','YES_NO',null],['CHILD','Operação','Portaria','YES_NO',JSON.stringify({item_id:tag+'-PARENT',answer:'Não'})],['QUESTION','Operação','Depósito','YES_NO',null],['NA','Operação','Depósito','YES_NO_NA',null],['ACTION','Plano de Ação','Depósito','ACTION_PLAN',null],['PAST','Verificação de Planos','Depósito','PLAN_REVIEW',null]];
  for(const [index,item] of items.entries())db.prepare('INSERT INTO template_items(id,template_id,code,title,area,section,response_type,expected_answer,condition_json,sort_order) VALUES(?,?,?,?,?,?,?,?,?,?)').run(tag+'-'+item[0],template,String(item[0]),String(item[0]),item[1],item[2],item[3],'Sim',item[4],index);
  for(const [suffix,date,status] of [['scheduled','2026-09-03','SCHEDULED'],['cancelled','2026-09-04','CANCELLED'],['outside','2026-10-03','SCHEDULED']]){const id=tag+'-'+suffix;visits.push(id);db.prepare('INSERT INTO visits(id,unit_id,visit_date,start_time,end_time,status,created_by) VALUES(?,?,?, ?,?,?,?)').run(id,unit,date,'08:00','09:00',status,coordId);}
  const source=inspection('source','2026-09-03','APPROVED');answer(source,'DOC','Não','NON_COMPLIANT',{},0);answer(source,'DOC','Sim','COMPLIANT');answer(source,'PARENT','Sim','COMPLIANT');answer(source,'CHILD','Não','NON_COMPLIANT');answer(source,'QUESTION','Não','NON_COMPLIANT');answer(source,'NA','Não se aplica','NOT_APPLICABLE');
  const planId=answer(source,'ACTION','Sim','COMPLIANT',{nonconformities:'Teste de pendência real',immediate:'Isolar',corrective:'Corrigir',preventive:'Verificar',responsible:'Equipe técnica'});
  const followup=inspection('followup','2026-09-15','IN_REVIEW');answer(followup,'PAST','Sim','COMPLIANT',{checks:[{id:planId,answer:'Sim',comment:'Concluído na visita'}]});
  inspection('other-assigned','2026-09-16','IN_REVIEW',otherTechId);inspection('draft','2026-09-17','IN_PROGRESS');inspection('cancelled-report','2026-09-18','CANCELLED');inspection('foreign-report','2026-09-19','APPROVED',techId,otherUnit,foreign);
  const filters={month:'2026-09',unit},monthly=monthlyStatistics(tech,filters);
  assert.equal(monthly.scheduled,1);assert.equal(monthly.received,2);assert.equal(monthly.approved,1);assert.deepEqual(monthly.counts,{answered:4,applicable:8,compliant:2,noncompliant:1,notApplicable:1,unclassified:0});assert.equal(monthly.reports.find(report=>report.id===source)!.answered,4);
  assert.deepEqual(monthly.uniqueCoverage,{answered:4,applicable:4});assert.equal(monthly.units[0].uniqueAnswered,4);assert.equal(monthly.units[0].uniqueApplicable,4);
  assert.equal(monthlyStatistics(coord,filters).received,3);assert.equal(monthlyStatistics(admin,filters).received,3);assert.equal(availableStatisticsUnit(tech,otherUnit),false);assert.throws(()=>monthlyStatistics(tech,{month:'2026-09',unit:otherUnit}));
  for(const [index,item] of ['DOC','PARENT','QUESTION','NA'].entries()){const partial=inspection('partial-'+index,`2026-08-${String(3+index*7).padStart(2,'0')}`,'IN_REVIEW');answer(partial,item,'Sim','COMPLIANT');}
  const partialMonth=monthlyStatistics(tech,{month:'2026-08',unit});assert.deepEqual(partialMonth.uniqueCoverage,{answered:4,applicable:4});assert.equal(partialMonth.counts.answered,4);assert.equal(partialMonth.counts.applicable,16);
  answer(tag+'-partial-3','DOC','Sim','COMPLIANT');assert.deepEqual(monthlyStatistics(tech,{month:'2026-08',unit}).uniqueCoverage,{answered:4,applicable:4});assert.equal(monthlyStatistics(tech,{month:'2026-08',unit}).counts.answered,5);
  const secondUnit=tag+'-second-unit';db.prepare('INSERT INTO units(id,company_id,name,code,responsible_id) VALUES(?,?,?,?,?)').run(secondUnit,company,secondUnit,secondUnit,techId);const secondUnitVisit=inspection('second-unit-visit','2026-08-04','IN_REVIEW',techId,secondUnit);answer(secondUnitVisit,'DOC','Sim','COMPLIANT');assert.deepEqual(monthlyStatistics(tech,{month:'2026-08',unit:''}).uniqueCoverage,{answered:5,applicable:8});
  assert.equal(trackedPlans(tech,filters)[0].completed,false);assert.equal(trackedPlans(tech,filters)[0].verification!.answer,'Sim');db.prepare("UPDATE inspections SET status='APPROVED' WHERE id=?").run(followup);assert.equal(trackedPlans(tech,filters)[0].completed,true);
  const latest=inspection('latest','2026-10-02','APPROVED');answer(latest,'PAST','Sim','COMPLIANT',{checks:[{id:planId,answer:'Não',comment:'Nova verificação encontrou pendência'}]});assert.equal(trackedPlans(tech,filters)[0].completed,false);assert.equal(trackedPlans(tech,filters)[0].verification!.inspection_id,latest);
  const badCheck=inspection('foreign-check','2026-10-03','APPROVED',techId,otherUnit,foreign);answer(badCheck,'PAST','Sim','COMPLIANT',{checks:[{id:planId,answer:'Sim',comment:'Não pode concluir plano de outra unidade'}]});assert.equal(trackedPlans(admin,filters)[0].completed,false);
  assert.equal((await request('/api/monthly-reports?mes=2026-09')).status,401);
  const login=await fetch('http://localhost:3000/api/auth/login',{method:'POST',body:new URLSearchParams({email:tech.email,password}),redirect:'manual'});assert.equal(login.status,303);const cookie=login.headers.get('set-cookie')!.split(';')[0];
  assert.equal((await request('/api/monthly-reports?mes=2026-13',cookie)).status,400);assert.equal((await request(`/api/monthly-reports?mes=2026-09&unidade=${otherUnit}`,cookie)).status,404);
  const pdfResponse=await request(`/api/monthly-reports?mes=2026-09&unidade=${unit}`,cookie);assert.equal(pdfResponse.status,200);assert.equal(pdfResponse.headers.get('content-type'),'application/pdf');const pdf=Buffer.from(await pdfResponse.arrayBuffer());assert.equal(pdf.subarray(0,5).toString(),'%PDF-');assert.equal([...pdf.toString('latin1').matchAll(/\/Type\s*\/Page\b/g)].length,2,'Rodapés não devem criar páginas extras');fs.mkdirSync('tmp',{recursive:true});fs.writeFileSync('tmp/monthly-report-test.pdf',pdf);
  const monthlyHtml=await (await request(`/relatorios-mensais?mes=2026-09&unidade=${unit}`,cookie)).text();assert.ok(monthlyHtml.includes('Preenchimento por modelo e área'));assert.ok(monthlyHtml.includes(source));assert.ok(!monthlyHtml.includes(tag+'-other-assigned'));const plansHtml=await (await request(`/planos-de-acao?mes=2026-09&unidade=${unit}`,cookie)).text();assert.ok(plansHtml.includes('Teste de pendência real'));assert.ok(plansHtml.includes('Nova verificação encontrou pendência'));
  console.log('Mensal e planos: cobertura mensal única por unidade/modelo, visitas parciais, repetição de itens, respostas atuais, condicionais, cancelamentos, classificação, escopo, verificações aprovadas, páginas e PDF validados.');
}finally{
  db.prepare('DELETE FROM audit_logs WHERE company_id IN (?,?)').run(company,foreign);
  for(const id of reports){for(const table of ['report_section_reviews','evidences','responses','nonconformities','inspection_sessions'])db.prepare(`DELETE FROM ${table} WHERE inspection_id=?`).run(id);db.prepare('DELETE FROM inspections WHERE id=?').run(id);}
  for(const id of visits)db.prepare('DELETE FROM visits WHERE id=?').run(id);
  db.prepare('DELETE FROM template_items WHERE template_id=?').run(template);db.prepare('DELETE FROM templates WHERE id=?').run(template);db.prepare('DELETE FROM units WHERE company_id IN (?,?)').run(company,foreign);db.prepare('DELETE FROM users WHERE company_id=?').run(company);db.prepare('DELETE FROM companies WHERE id IN (?,?)').run(company,foreign);
}
