import Link from 'next/link';
import {redirect} from 'next/navigation';
import {currentUser} from '@/lib/auth';
import {db} from '@/lib/db';
import {AppShell} from '@/components/app-shell';
import {ClipboardCheck,TriangleAlert,Clock3,CheckCircle2,Plus,ArrowRight} from 'lucide-react';
import {statusLabel} from '@/lib/utils';
type Inspection={id:string;control_code:string;title:string;status:string;progress:number;unit_name:string;planned_start:string};
export default async function Dashboard(){
 const user=await currentUser();if(!user)redirect('/login');
 const where=user.role==='SUPER_ADMIN'?'1=1':user.role==='INSPECTOR'?'i.inspector_id=?':'i.company_id=?';
 const statement=db.prepare(`SELECT i.*,u.name unit_name FROM inspections i JOIN units u ON u.id=i.unit_id WHERE ${where} ORDER BY i.updated_at DESC`);
 const inspections=(user.role==='SUPER_ADMIN'?statement.all():statement.all(user.role==='INSPECTOR'?user.id:user.company_id)) as Inspection[];
 const ncWhere=user.role==='SUPER_ADMIN'?'1=1':user.role==='INSPECTOR'?'i.inspector_id=?':'i.company_id=?';
 const ncSql=`SELECT count(*) n FROM nonconformities n JOIN inspections i ON i.id=n.inspection_id WHERE n.status='OPEN' AND ${ncWhere}`;
 const openNc=(user.role==='SUPER_ADMIN'?db.prepare(ncSql).get():db.prepare(ncSql).get(user.role==='INSPECTOR'?user.id:user.company_id)) as {n:number};
 const activityWhere=user.role==='SUPER_ADMIN'?'1=1':user.role==='INSPECTOR'?'(a.user_id=? OR i.inspector_id=?)':'a.company_id=?';
 const activityStatement=db.prepare(`SELECT a.action,a.entity_type,a.created_at FROM audit_logs a LEFT JOIN inspections i ON i.id=a.inspection_id WHERE ${activityWhere} ORDER BY a.created_at DESC LIMIT 5`);
 const activities=(user.role==='SUPER_ADMIN'?activityStatement.all():user.role==='INSPECTOR'?activityStatement.all(user.id,user.id):activityStatement.all(user.company_id)) as {action:string;entity_type:string;created_at:string}[];
 const inProgress=inspections.filter(i=>i.status==='IN_PROGRESS').length,completed=inspections.filter(i=>['APPROVED','REPORT_PUBLISHED'].includes(i.status)).length;
 return <AppShell user={user}><header className="topbar"><div><div className="eyebrow">{new Intl.DateTimeFormat('pt-BR',{weekday:'long',day:'2-digit',month:'long'}).format(new Date())}</div><h1 className="title">Olá, {user.name.split(' ')[0]}</h1></div>{user.role!=='INSPECTOR'&&<Link className="btn btn-primary" href="/inspecoes/nova"><Plus size={16}/>Nova inspeção</Link>}</header><section className="grid stats"><Stat label="Em andamento" value={inProgress} note="inspeções ativas" icon={<ClipboardCheck/>}/><Stat label="Não conformidades" value={openNc.n} note="aguardando ação" icon={<TriangleAlert/>}/><Stat label="Programadas" value={inspections.filter(i=>i.status==='SCHEDULED').length} note="próximas visitas" icon={<Clock3/>}/><Stat label="Concluídas" value={completed} note="neste ciclo" icon={<CheckCircle2/>}/></section><div className="grid two-col"><section><div className="section-head"><div><h2>Inspeções recentes</h2><p>Acompanhe o andamento das operações.</p></div><Link className="btn btn-ghost" href="/inspecoes">Ver todas <ArrowRight size={14}/></Link></div><div className="card inspection-list">{inspections.length?inspections.slice(0,5).map(i=><Link className="inspection-row" key={i.id} href={`/inspecoes/${i.id}`}><div><div className="inspection-name">{i.title}</div><div className="muted">{i.control_code} · {i.unit_name}</div></div><span className={'badge '+(i.status==='IN_PROGRESS'?'success':'')}>{statusLabel(i.status)}</span><div><div className="muted" style={{marginBottom:6}}>Progresso · {i.progress}%</div><div className="progress"><span style={{width:`${i.progress}%`}}/></div></div><span className="btn btn-soft">Abrir</span></Link>):<div className="muted">Nenhuma inspeção disponível.</div>}</div></section><aside><div className="section-head"><div><h2>Atividade recente</h2><p>Rastreabilidade da operação.</p></div></div><div className="card activity">{activities.length?activities.map((a,n)=><div className="activity-item" key={n}><span className="dot"/><div><b>{a.action.replaceAll('_',' ')}</b><div className="muted">{a.entity_type} · {new Date(a.created_at+'Z').toLocaleString('pt-BR')}</div></div></div>):<div className="muted">As atividades aparecerão aqui.</div>}</div></aside></div></AppShell>;
}
function Stat({label,value,note,icon}:{label:string;value:number;note:string;icon:React.ReactNode}){return <div className="card"><div className="stat-head"><span>{label}</span><span className="icon-chip">{icon}</span></div><div className="stat-value">{String(value).padStart(2,'0')}</div><div className="stat-note">{note}</div></div>}
