import Link from 'next/link';
import {notFound,redirect} from 'next/navigation';
import {Camera,Mic,Pencil,Plus} from 'lucide-react';
import {currentUser} from '@/lib/auth';
import {db} from '@/lib/db';
import {AppShell} from '@/components/app-shell';
import {ConfirmSubmit} from '@/components/confirm-submit';

type Template={id:string;company_id:string|null;name:string;category:string|null;description:string|null;version:number;status:string;is_global:number};
type Item={id:string;area:string;section:string|null;code:string;title:string;guidance:string|null;criticality:string;expected_answer:string|null;photo_required:number;audio_required:number;sort_order:number};
const templateStatus=(status:string)=>status==='PUBLISHED'?'Publicado':status==='ARCHIVED'?'Arquivado':'Rascunho';

export default async function TemplateDetails({params,searchParams}:{params:Promise<{id:string}>;searchParams:Promise<{ok?:string;erro?:string}>}){
  const user=await currentUser();if(!user)redirect('/login');
  const {id}=await params;
  const template=db.prepare('SELECT * FROM templates WHERE id=?').get(id) as Template|undefined;
  if(!template||(user.role!=='SUPER_ADMIN'&&!template.is_global&&template.company_id!==user.company_id))notFound();
  const items=db.prepare('SELECT * FROM template_items WHERE template_id=? AND active=1 ORDER BY sort_order').all(id) as Item[];
  const canEdit=user.role!=='INSPECTOR'&&!template.is_global&&(user.role==='SUPER_ADMIN'||template.company_id===user.company_id);
  const query=await searchParams;
  return <AppShell user={user} active="templates"><header className="topbar"><div><div className="eyebrow">{template.category||'Modelo'} · versão {template.version}</div><h1 className="title">{template.name}</h1></div><span className={'badge '+(template.status==='PUBLISHED'?'success':template.status==='ARCHIVED'?'warn':'')}>{templateStatus(template.status)}</span></header>
    {query.ok&&<div className="notice success-notice">{query.ok==='item-excluido'?'Item excluído das próximas inspeções. O histórico foi preservado.':query.ok==='modelo-arquivado'?'Modelo arquivado. Inspeções anteriores continuam disponíveis.':'Alterações salvas com sucesso.'}</div>}{query.erro&&<div className="error">{query.erro==='itens'?'Adicione ao menos um item antes de publicar o modelo.':'Não foi possível salvar. Revise os campos.'}</div>}
    {canEdit?<form className="card form-card" action={`/api/templates/${id}`} method="post"><input type="hidden" name="intent" value="update"/><div className="grid form-grid"><div className="field field-wide"><label>NOME DO MODELO</label><input name="name" required minLength={3} defaultValue={template.name}/></div><div className="field"><label>CATEGORIA</label><input name="category" required defaultValue={template.category||''}/></div><div className="field"><label>STATUS</label><select name="status" defaultValue={template.status==='ARCHIVED'?'DRAFT':template.status}><option value="DRAFT">Rascunho</option><option value="PUBLISHED">Publicado</option></select>{template.status==='ARCHIVED'&&<small className="muted">Salve como rascunho ou publicado para reativar.</small>}</div><div className="field field-wide"><label>DESCRIÇÃO</label><textarea name="description" rows={3} defaultValue={template.description||''}/></div></div><div className="form-actions"><Link className="btn btn-ghost" href="/modelos">Voltar</Link><button className="btn btn-primary">Salvar modelo</button></div></form>:<section className="card"><p style={{marginTop:0}}>{template.description||'Sem descrição.'}</p><div className="entity-meta"><span>{items.length} itens ativos</span><span>Versão {template.version}</span></div></section>}
    <div className="section-head"><div><h2>Itens de verificação</h2><p>Editar afeta somente futuras inspeções; inspeções já criadas são imutáveis.</p></div></div>
    <div className="grid">{items.map((item,index)=><div className="card checklist-item" key={item.id}><div className="check-index">{String(index+1).padStart(2,'0')}</div><div><div className="eyebrow">{item.area} · {item.code}</div><h3>{item.title}</h3><p className="muted">{item.guidance||'Sem orientação adicional.'}</p><div className="evidence-pills"><span className="badge">{item.criticality}</span>{item.photo_required===1&&<span className="badge success"><Camera size={12}/>Foto obrigatória</span>}{item.audio_required===1&&<span className="badge success"><Mic size={12}/>Áudio obrigatório</span>}<span className="badge">Esperado: {item.expected_answer||'—'}</span></div></div>{canEdit&&<div className="item-actions"><Link className="btn btn-ghost" href={`/modelos/${id}/itens/${item.id}`}><Pencil size={14}/>Editar</Link><form action={`/api/templates/${id}/items/${item.id}`} method="post"><input type="hidden" name="intent" value="delete"/><ConfirmSubmit label="Excluir" message={`Excluir o item ${item.code} das próximas inspeções? O histórico existente será preservado.`}/></form></div>}</div>)}{!items.length&&<div className="card empty-state"><h2>Nenhum item ativo</h2><p>Adicione uma verificação para montar o roteiro.</p></div>}</div>
    {canEdit&&<><div className="section-head"><div><h2>Adicionar item</h2><p>Inclua uma nova verificação neste modelo.</p></div></div><form className="card form-card" action={`/api/templates/${id}/items`} method="post"><div className="grid form-grid"><div className="field"><label>ÁREA</label><input name="area" required/></div><div className="field"><label>SEÇÃO</label><input name="section"/></div><div className="field"><label>CÓDIGO</label><input name="code" required placeholder="Ex.: SEG-01"/></div><div className="field"><label>CRITICIDADE</label><select name="criticality"><option value="LOW">Baixa</option><option value="MEDIUM">Média</option><option value="HIGH">Alta</option><option value="CRITICAL">Crítica</option></select></div><div className="field field-wide"><label>PERGUNTA / VERIFICAÇÃO</label><input name="title" required minLength={5}/></div><div className="field field-wide"><label>ORIENTAÇÃO AO INSPETOR</label><textarea name="guidance" rows={3}/></div><div className="field"><label>RESPOSTA ESPERADA</label><select name="expected_answer"><option>Sim</option><option>Não</option><option>Não se aplica</option></select></div><div className="field"><label>EVIDÊNCIAS OBRIGATÓRIAS</label><label className="check-option"><input type="checkbox" name="photo_required" value="1"/> Foto</label><label className="check-option"><input type="checkbox" name="audio_required" value="1"/> Áudio</label></div></div><div className="form-actions"><Link className="btn btn-ghost" href="/modelos">Voltar</Link><button className="btn btn-primary"><Plus size={15}/>Adicionar item</button></div></form>
      {template.status!=='ARCHIVED'&&<form className="danger-zone" action={`/api/templates/${id}`} method="post"><input type="hidden" name="intent" value="archive"/><div><b>Arquivar modelo</b><p>Ele deixará de ser oferecido em novas inspeções. Todo histórico continuará disponível.</p></div><ConfirmSubmit label="Arquivar modelo" message="Arquivar este modelo? As inspeções existentes não serão alteradas."/></form>}
    </>}
  </AppShell>;
}
